lyft/protoc-gen-star

- README.md
- plugin.go
This patch ensures that the `GenerateImports` output from `PluginBase` is stably sorted, using `text/template` instead of iterating over the import map.
> Plugin Imports: ensure stable output of imports for plugins

- .travis.yml
- Makefile
- glide.lock
- glide.yaml
This patch pins the current code to protoc-gen-go < v1.1.0 as that version introduces a breaking change. This change effectively bumps the PGG dep to v1.0.0.
See #13 for context. A later patch will provide support for PGG >= v1.1.0
> Pin protoc-gen-go version < 1.1.0

- .travis.yml
- gatherer.go
- gatherer_test.go
- glide.lock
- glide.yaml
- package.go
- parameters.go
- parameters_test.go
- path.go
- path_test.go
- plugin_test.go
- protoc_gen_go.go
- protoc_gen_go_test.go
- workflow_multipackage_test.go
Fixes #13 
This is the first pass at supporting v1.1.0 of the protobuf lib. Had to disable/skip some of the tests on account of the lib changing its internal behavior + turn of the parallelism on others to prevent certain races due to use of globals.
Long(est) term solution is to remove the dependency on the lib entirely and just build up the struct and ASTs ourselves. This should address the issues we have now at the very least.
> Support protobuf v1.1.0

- lang/go/context.go
- lang/go/name.go
- lang/go/name_test.go
This patch adds the ServerStream helper to pgsgo.Context to enable resolving the grpc.ServerStream wrapper for client/server/bidi streaming methods. It also exports the PGGUpperCamelCase function for camel-casing following the same pattern as protoc-gen-go.
> Add ServerStream method to pgsgo context

- lang/go/name_test.go
- lang/go/package.go
- lang/go/testdata/names/entities/entities.proto
protoc-gen-go replaces all bad characters in the go_package option to underscores. This patch fixes that behavior in the pgsgo.Context.
> bad chars in go_package name

- .travis.yml
When pushing a branch to my fork, a travis run will be kicked of, but
it'll fail -- since `github.com/<me>/protoc-gen-star` is nothing like
`github.com/lyft/protoc-gen-star`.
This addition to .travis.yml should fix this.
See [before 💥](https://travis-ci.com/srenatus/protoc-gen-star/builds/85390296) and [after ✅ ](https://travis-ci.com/srenatus/protoc-gen-star/builds/85390958) 😉
> travis: fix building branches of PRs

- artifact.go
- module.go
- module_test.go
- persister.go
- persister_test.go
This way, non-critical errors can be returned by calling m.AddError.
Fixes #34.
> Add `GeneratorError` Artifact, expose it to modules via ModuleBase

- lang/go/package.go
- lang/go/package_test.go
- lang/go/testdata/names/import_path_mapped/import_path_mapped.proto
- lang/go/testdata/names/import_path_mapped/params
If the `import_path` param, `M` mapping param and `go_package` option are all set, the `go_package` option determines the name of the package. This patch fixes incorrect behavior here where import_path was overriding the value.
> go: go_package option overrides import_path parameter

- lang/go/name.go
- lang/go/name_test.go
- lang/go/testdata/names/entities/entities.proto
This patch addresses the following case in Go. Given the following protos:
```proto
message Foo {
message Bar {}
enum Baz { VALUE = 0; }
oneof some_oneof {
bool bar = 1;
int32 baz = 2;
}
}
```
The `some_oneof` field on the generated struct will have an interface type that is satisfied by two wrapper classes around the `bar` and `baz` fields typically named `Foo_Bar` and `Foo_Baz`, respectively. However, because there are a nested message and enum with those same names, the oneof wrappers' names should be suffixed with an underscore: `Foo_Bar_` and `Foo_Baz_`.
> go: name collisions with oneof fields and nested messages/enums

- lang/go/Makefile
- lang/go/package.go
- lang/go/package_test.go
- lang/go/testdata/names/import_path_mapped/params
- lang/go/testdata/names/transitive_package/other.proto
- lang/go/testdata/names/transitive_package/params
- lang/go/testdata/names/transitive_package/transitive.proto
protoc-gen-go can only operate against a single (go) package's proto files at the same time, so is able to resolve the `go_package` option off of any file to apply it to all files in the same execution (it likely assumes they are all the same and probably checks it during its code generation).
This patch adds this behavior to PG*'s go-specific tooling, but will only check the files in the same proto package for a go_package option since PG* is not limited to running against a single package.
> go_package: resolve package name transitively from other files in same execution

- protoc-gen-debug/main.go
This patch fixes PGD to properly write a file into a directory that does not exist. Also fixes erroneous error handling that wasn't checking the result of the output file being written.
> protoc-gen-debug: create dir before writing file

- ast.go
- ast_test.go
- file.go
- testdata/graph/packageless/packageless.proto
This patch adds support for packageless (or root scoped) entities. Original FQN builder always assumed a package would be specified (admittedly because I didn't know it was legal to _not_ have a package stanza). 
@charlievieth @twoism 
Fixes #42
> AST: special case packageless (root) entity FQNs

- extension_test.go
- file.go
- file_test.go
- message.go
- message_test.go
Previously, extensions were not being visited by `Walk()` because they were not included on File and Message's `accept()`.
> include extensions in accept()

- ast.go
- file.go
- file_test.go
`file.imports()` should include the file dependencies from the file descriptor. i added this functionality to `ProcessCodeGeneratorRequest` instead of `hydrateFile` to make sure all the dependency files have been hydrated.
> include file dependencies in imports()

- ast.go
- ast_test.go
- dependents.go
- dependents_test.go
- enum.go
- enum_test.go
- file.go
- file_test.go
- message.go
- message_test.go
This PR updates the File, Message, and Enum interfaces to include a reference to their dependents (Entities that require the given Entity) via Dependents(). File dependents are any file that directly or transitively imports the file. Message and enum dependents are any Message where it was used directly or transitively. 
A file's dependents will be always be available, but a full list of dependents for messages and enums will only be accessible if the AST was constructed by ProcessCodeGeneratorRequestBidirectional or ProcessFileDescriptorSetBidirectional. 
The slice of dependent messages is cached on a given Enum/Message on the first call to Dependents() to ensure that the complete list of dependents is cached. This cannot be done during hydration as the dependent references outside of …
> add file, enum, and message dependents

- entity.go
Previously the comment for `Extension()` didn't match the behavior of the implementation https://github.com/lyft/protoc-gen-star/blob/master/extension.go#L75
> update `Extension()`documentation to match behavior

- lang/go/type_name.go
- lang/go/type_name_test.go
Export `TypeName.IsPointer()`, which can be quite useful in various scenarios.
Extracted from #51
> lang/go: Add TypeName.IsPointer()

- .travis.yml
- Makefile
- ast.go
- ast_test.go
- file.go
- file_test.go
this PR fixes two bugs related to file.imports() and simplifies pulling in a file's dependencies
- file.imports() will now pull in all transitive dependencies, rather than just immediate dependencies
- file.imports() correctly pulls in all immediate dependencies via file.descriptor.GetDependency() removing the need to check a file's messages and services for additional imports
- updates `go vet` command and go version https://golang.org/doc/go1.12#vet
> file.imports() pulls in all transitive dependencies

- file_test.go
- lang/go/camel.go
- lang/go/name.go
This package is deprecated and will be removed in the future, see https://github.com/golang/protobuf/blob/b5de78c91d0d09482d65f0a96927631cd343d7bb/protoc-gen-go/generator/generator.go#L42-L47.
This PR copies in the `generator.CamelCase` method, much the same as https://github.com/grpc-ecosystem/grpc-gateway/pull/1260.
> Clean up usage of deprecated protoc-gen-go/generator

- persister.go
- persister_test.go
Fixed `insertAppend` to insert artifacts at the end of the file.
This is a fix proposal for #73
> persister: fix append files

- entity.go
- file.go
- file_test.go
This patch ensures that the behavior of the `Imports` method on `Entity` is consistent across all entities. `Imports` on `File` was recently updated to include transitive behavior, breaking downstream tools relying on the original behavior. To make sure that `Import` behaves consistently, the prior behavior is returned while a new `TransitiveImports` method has been added to `File`. A later patch will make `Dependents` has a similarly consistent behavior.
> Make Imports consistent; add TransitiveImports for the whole tree

- go.mod
- go.sum
- message_test.go
- tools.go
There was an errant reference to the old [github.com/golang/protobuf](http://github.com/golang/protobuf) package, which https://github.com/lyft/protoc-gen-star/pull/113 aimed to remove. I missed that pg*’s go.mod still had that package.
> Remove reference to github.com/golang/protobuf

- Makefile
- README.md
- remove vendor and glide from Makefile
- remove glide link from readme
> makefile cleanup

- ast.go
- ast_test.go
- message.go
- message_test.go
While parsing and assigning dependencies, we can store both directions
of dependency information. This allows simple resolution from a message
-> all messages within its definition.
> Add Dependency info to supplement Dependents
